workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
  jobs:
    build:
      docker:
        - image: circleci/openjdk:8-jdk-browsers
      
      working_directory: ~/GoogleCloudTask/src/test/java 

      steps: 

        - checkout 
      
        - run: mvn dependency:go-offline 
      
        - run: mvn test -Dtest=tst* -Dbrowser=${BROWSER}
      
        - store_test_results: 
            path: target/surefire-reports