version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/GoogleCloudTask 

    steps: 

      - checkout 
      
      - run: mvn dependency:go-offline 
      
      - run: mvn package
      
      - store_test_results: 
          path: target/surefire-reports