version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test_job:
        docker:
          - image: circleci/openjdk:8-jdk-browsers
      
        working_directory: ~/GoogleCloudTask/src/test/java 

        steps: 

          - checkout 
      
          - run: mvn dependency:go-offline 
      
          - run: mvn test -Dtest=tst* -Dbrowser=${BROWSER}
      
          - store_test_results: 
              path: target/surefire-reports

workflows:
  version: 2
  build-test:
    jobs:
      - test_job