version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/GoogleCloudTask/src/test/java 

    steps: 

      - checkout 
      
      - run: mvn dependency:go-offline 
      
      - run: mvn test -Dtest=tstGoogleCloudForm
      
      - store_test_results: 
          path: target/surefire-reports